### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by PrakashIrom** [dimpeshpanwar/KOTLIN-Programs#4]
Hey I would like to know is this repo part of the Hacktoberfest-2024 and what kind of kotlin programs I can contribute to?

**Comment by dimpeshpanwar** [comment]
yes this is part of Hactoberfest2024 and every type of kotlin programs allowed.
first you have to follow then PR approved.

**Comment by PrakashIrom** [comment]
hey I did a pr on this repo could you please check?

**Comment by dimpeshpanwar** [comment]
### **accepted**
